name: 'Chromatic Deployment'

on:
  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - run: |
          yarn config set nodeLinker "node-modules"
          yarn install --immutable

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
